# Wrangle data {.tabset .tabset-sticky}

```{r message=FALSE, warning=FALSE}
source("0_helpers.R")
```

## Load data

```{r}
msleep = readRDS("msleep_processed.rds")
```

## Descriptives {.active}
```{r warning=FALSE}
msleep %>% 
	select(sleep_total, sleep_rem, brainwt, bodywt) %>% 
	summarise_all_vars()
```

## Distributions

```{r}
qplot(eats, data = msleep)
qplot(sleep_total, data = msleep, binwidth = 0.5)
qplot(sleep_rem, data = msleep, binwidth = 0.5)
qplot(sleep_total, sleep_rem, data = msleep)
ph = function (x, ..., row.names = FALSE, dont_transform = "knit_asis") {
    anyS3method = function(x) {
        classes = class(x)
        any(sapply(classes, FUN = function(classes) {
            !is.null(utils::getS3method("pander", classes, TRUE, 
                environment(pander::pander)))
        }))
    }
    if (length(intersect(dont_transform, class(x))) > 0) {
       res = withVisible(knit_print(x, ...))
	    # indicate the htmlwidget result with a special class so we can attach
	    # the figure caption to it later in wrap.knit_asis
	    if (inherits(x, 'htmlwidget'))
	      class(res$value) = c(class(res$value), 'knit_asis_htmlwidget')
	    if (res$visible) res$value else invisible(res$value)
    }
    else if (anyS3method(x)) {
        pander::pander(x, row.names = row.names, ...)
    }
    else if (isS4(x)) {
        methods::show(x)
    }
    else {
    res = withVisible(knit_print(x, ...))
    # indicate the htmlwidget result with a special class so we can attach
    # the figure caption to it later in wrap.knit_asis
    if (inherits(x, 'htmlwidget'))
      class(res$value) = c(class(res$value), 'knit_asis_htmlwidget')
    if (res$visible) res$value else invisible(res$value)
    }
}
	

```

## Look at the data

```{r render=ph}
library(DT)
datatable(msleep, 
	filter = 'top', options = list(
  pageLength = 50, autoWidth = TRUE
), rownames = F)
```

